name:                betitla
version:             0.1.0.0
github:              "jmagee/betitla"
license:             BSD2
author:              "Josh Magee"
maintainer:          "magee.joshua@yahoo.com"
copyright:           "2022 Joshua Magee"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jmagee/betitla#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: lib
  dependencies:
    - QuickCheck
    - aeson
    - bytestring
    - containers
    - directory
    - path
    - random
    - random-shuffle
    - strive
    - time
    - transformers

executables:
  betitla-renamer:
    main:                betitla-renamer.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - betitla

tests:
  betitla-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists
    dependencies:
    - QuickCheck
    - betitla
    - hspec
